/**
 * Pre-computed token constants for use across all packages.
 *
 * Each constant is a CSS `var()` reference generated by the corresponding
 * helper function. Import these instead of calling `semanticVar()`,
 * `colorVar()`, etc. in every component file.
 *
 * Naming conventions:
 * - Spacing: `SP_` + scale step with underscores for decimals (SP_1_25 = step 1.25)
 * - Colors: `{FAMILY}_{STEP}` (BLUE_60, GRAY_110)
 * - Semantic: descriptive name matching the token group/key (TEXT_PRIMARY, BORDER_FOCUS)
 * - Shape: `RADIUS_` / `BW_` prefix
 * - Elevation: `ELEVATION_` + level
 */

import {
  semanticVar,
  colorVar,
  spaceVar,
  radiusVar,
  borderWidthVar,
  elevationVar,
  typeBlock,
} from "./tokens.js";

// ─── Text ───────────────────────────────────────────────────────────────────

export const TEXT_PRIMARY = semanticVar("text", "primary");
export const TEXT_SECONDARY = semanticVar("text", "secondary");
export const TEXT_TERTIARY = semanticVar("text", "tertiary");
export const TEXT_LINK = semanticVar("text", "link");
export const TEXT_LINK_HOVER = semanticVar("text", "linkHover");
export const TEXT_LINK_ACTIVE = semanticVar("text", "linkActive");
export const TEXT_VISITED = semanticVar("text", "visited");
export const TEXT_SELECTED = semanticVar("text", "selected");
export const TEXT_REVERSED = semanticVar("text", "reversed");

// ─── Surface ────────────────────────────────────────────────────────────────

export const SURFACE_PRIMARY = semanticVar("surface", "primary");
export const SURFACE_SECONDARY = semanticVar("surface", "secondary");
export const SURFACE_TERTIARY = semanticVar("surface", "tertiary");
export const SURFACE_BOLD = semanticVar("surface", "bold");
export const SURFACE_ACTION = semanticVar("surface", "action");
export const SURFACE_ACTION_CONTRAST = semanticVar("surface", "actionContrast");
export const SURFACE_DESTRUCTIVE = semanticVar("surface", "destructive");
export const SURFACE_SUCCESS = semanticVar("surface", "success");
export const SURFACE_CONTRAST = semanticVar("surface", "contrast");
export const SURFACE_OVERLAY = semanticVar("surface", "overlay");

// ─── Icon ───────────────────────────────────────────────────────────────────

export const ICON_PRIMARY = semanticVar("icon", "primary");
export const ICON_SECONDARY = semanticVar("icon", "secondary");
export const ICON_ACTION = semanticVar("icon", "action");
export const ICON_REVERSED = semanticVar("icon", "reversed");

// ─── Border ─────────────────────────────────────────────────────────────────

export const BORDER_MINIMAL = semanticVar("border", "minimal");
export const BORDER_SUBTLE = semanticVar("border", "subtle");
export const BORDER_MODERATE = semanticVar("border", "moderate");
export const BORDER_BOLD = semanticVar("border", "bold");
export const BORDER_CONTRAST = semanticVar("border", "contrast");
export const BORDER_FOCUS = semanticVar("border", "focus");

// ─── Form ───────────────────────────────────────────────────────────────────

export const FORM_INPUT_BORDER = semanticVar("form", "inputBorder");

// ─── Button ─────────────────────────────────────────────────────────────────

export const BUTTON_SECONDARY = semanticVar("button", "secondary");

// ─── Tag ────────────────────────────────────────────────────────────────────

export const TAG_BOLD = semanticVar("tag", "bold");
export const TAG_SUBTLE = semanticVar("tag", "subtle");
export const TAG_TEXT_BOLD = semanticVar("tag", "textBold");
export const TAG_TEXT_SUBTLE = semanticVar("tag", "textSubtle");
export const TAG_TEXT_MINIMAL = semanticVar("tag", "textMinimal");

// ─── State: Hover ───────────────────────────────────────────────────────────

export const HOVER_BORDER_MODERATE = semanticVar("stateHover", "borderModerate");
export const HOVER_MINIMAL = semanticVar("stateHover", "surfaceMinimal");
export const HOVER_MODERATE = semanticVar("stateHover", "surfaceModerate");
export const HOVER_BOLD = semanticVar("stateHover", "surfaceBold");
export const HOVER_SUBTLE = semanticVar("stateHover", "surfaceSubtle");

// ─── State: Active ──────────────────────────────────────────────────────────

export const ACTIVE_BOLD = semanticVar("stateActive", "surfaceBold");
export const ACTIVE_SUBTLE = semanticVar("stateActive", "surfaceSubtle");

// ─── State: Selected ────────────────────────────────────────────────────────

export const SELECTED_BOLD = semanticVar("stateSelected", "surfaceBold");
export const SELECTED_MINIMAL = semanticVar("stateSelected", "surfaceMinimal");
export const SELECTED_OVERLAY = semanticVar("stateSelected", "surfaceOverlay");

// ─── State: Disabled ────────────────────────────────────────────────────────

export const DISABLED_TEXT = semanticVar("stateDisabled", "text");
export const DISABLED_BORDER = semanticVar("stateDisabled", "border");
export const DISABLED_MINIMAL = semanticVar("stateDisabled", "minimal");

// ─── Grid Row ───────────────────────────────────────────────────────────────

export const GRID_ROW_DEFAULT = semanticVar("gridRow", "rowDefault");
export const GRID_ROW_SELECTED = semanticVar("gridRow", "rowSelected");
export const GRID_ROW_ALT = semanticVar("gridRow", "rowAlt");

// ─── Status: General ────────────────────────────────────────────────────────

export const STATUS_GENERAL_ERROR = semanticVar("statusGeneral", "error");
export const STATUS_GENERAL_WARNING = semanticVar("statusGeneral", "warning");
export const STATUS_GENERAL_SUCCESS = semanticVar("statusGeneral", "success");

// ─── Status: Surface (Bold) ─────────────────────────────────────────────────

export const STATUS_SURFACE_NONE_BOLD = semanticVar("statusSurface", "noneBold");
export const STATUS_SURFACE_INFO_BOLD = semanticVar("statusSurface", "informationBold");
export const STATUS_SURFACE_SUCCESS_BOLD = semanticVar("statusSurface", "successBold");
export const STATUS_SURFACE_ERROR_BOLD = semanticVar("statusSurface", "errorBold");
export const STATUS_SURFACE_WARNING_BOLD = semanticVar("statusSurface", "warningBold");
export const STATUS_SURFACE_OPEN_BOLD = semanticVar("statusSurface", "openBold");
export const STATUS_SURFACE_COMPLETE_BOLD = semanticVar("statusSurface", "completeBold");
export const STATUS_SURFACE_SUSPENDED_BOLD = semanticVar("statusSurface", "suspendedBold");
export const STATUS_SURFACE_CANCELLED_BOLD = semanticVar("statusSurface", "cancelledBold");

// ─── Status: Surface (Subtle) ───────────────────────────────────────────────

export const STATUS_SURFACE_NONE_SUBTLE = semanticVar("statusSurface", "noneSubtle");
export const STATUS_SURFACE_INFO_SUBTLE = semanticVar("statusSurface", "informationSubtle");
export const STATUS_SURFACE_SUCCESS_SUBTLE = semanticVar("statusSurface", "successSubtle");
export const STATUS_SURFACE_ERROR_SUBTLE = semanticVar("statusSurface", "errorSubtle");
export const STATUS_SURFACE_WARNING_SUBTLE = semanticVar("statusSurface", "warningSubtle");
export const STATUS_SURFACE_OPEN_SUBTLE = semanticVar("statusSurface", "openSubtle");
export const STATUS_SURFACE_COMPLETE_SUBTLE = semanticVar("statusSurface", "completeSubtle");
export const STATUS_SURFACE_SUSPENDED_SUBTLE = semanticVar("statusSurface", "suspendedSubtle");
export const STATUS_SURFACE_CANCELLED_SUBTLE = semanticVar("statusSurface", "cancelledSubtle");

// ─── Status: Text (Bold) ────────────────────────────────────────────────────

export const STATUS_TEXT_NONE_BOLD = semanticVar("statusText", "noneBoldText");
export const STATUS_TEXT_INFO_BOLD = semanticVar("statusText", "informationBoldText");
export const STATUS_TEXT_SUCCESS_BOLD = semanticVar("statusText", "successBoldText");
export const STATUS_TEXT_ERROR_BOLD = semanticVar("statusText", "errorBoldText");
export const STATUS_TEXT_WARNING_BOLD = semanticVar("statusText", "warningBoldText");

// ─── Status: Text (Subtle) ──────────────────────────────────────────────────

export const STATUS_TEXT_NONE_SUBTLE = semanticVar("statusText", "noneSubtleText");
export const STATUS_TEXT_INFO_SUBTLE = semanticVar("statusText", "informationSubtleText");
export const STATUS_TEXT_SUCCESS_SUBTLE = semanticVar("statusText", "successSubtleText");
export const STATUS_TEXT_ERROR_SUBTLE = semanticVar("statusText", "errorSubtleText");
export const STATUS_TEXT_WARNING_SUBTLE = semanticVar("statusText", "warningSubtleText");

// ─── Status: Icon (Bold) ────────────────────────────────────────────────────

export const STATUS_ICON_NONE_BOLD = semanticVar("statusIcon", "noneBoldIcon");
export const STATUS_ICON_INFO_BOLD = semanticVar("statusIcon", "informationBoldIcon");
export const STATUS_ICON_SUCCESS_BOLD = semanticVar("statusIcon", "successBoldIcon");
export const STATUS_ICON_ERROR_BOLD = semanticVar("statusIcon", "errorBoldIcon");
export const STATUS_ICON_WARNING_BOLD = semanticVar("statusIcon", "warningBoldIcon");

// ─── Status: Icon (Subtle) ──────────────────────────────────────────────────

export const STATUS_ICON_NONE_SUBTLE = semanticVar("statusIcon", "noneSubtleIcon");
export const STATUS_ICON_INFO_SUBTLE = semanticVar("statusIcon", "informationSubtleIcon");
export const STATUS_ICON_SUCCESS_SUBTLE = semanticVar("statusIcon", "successSubtleIcon");
export const STATUS_ICON_ERROR_SUBTLE = semanticVar("statusIcon", "errorSubtleIcon");
export const STATUS_ICON_WARNING_SUBTLE = semanticVar("statusIcon", "warningSubtleIcon");

// ─── Color: Blue ────────────────────────────────────────────────────────────

export const BLUE_20 = colorVar("blue", 20);
export const BLUE_30 = colorVar("blue", 30);
export const BLUE_40 = colorVar("blue", 40);
export const BLUE_60 = colorVar("blue", 60);
export const BLUE_70 = colorVar("blue", 70);

// ─── Color: Green ───────────────────────────────────────────────────────────

export const GREEN_20 = colorVar("green", 20);
export const GREEN_60 = colorVar("green", 60);
export const GREEN_70 = colorVar("green", 70);

// ─── Color: Red ─────────────────────────────────────────────────────────────

export const RED_20 = colorVar("red", 20);
export const RED_60 = colorVar("red", 60);
export const RED_70 = colorVar("red", 70);

// ─── Color: Orange ──────────────────────────────────────────────────────────

export const ORANGE_20 = colorVar("orange", 20);
export const ORANGE_60 = colorVar("orange", 60);
export const ORANGE_70 = colorVar("orange", 70);

// ─── Color: Yellow ──────────────────────────────────────────────────────────

export const YELLOW_10 = colorVar("yellow", 10);
export const YELLOW_30 = colorVar("yellow", 30);

// ─── Color: Lime ────────────────────────────────────────────────────────────

export const LIME_20 = colorVar("lime", 20);
export const LIME_60 = colorVar("lime", 60);
export const LIME_70 = colorVar("lime", 70);

// ─── Color: Teal ────────────────────────────────────────────────────────────

export const TEAL_20 = colorVar("teal", 20);
export const TEAL_60 = colorVar("teal", 60);
export const TEAL_70 = colorVar("teal", 70);

// ─── Color: Turquoise ──────────────────────────────────────────────────────

export const TURQUOISE_20 = colorVar("turquoise", 20);
export const TURQUOISE_60 = colorVar("turquoise", 60);
export const TURQUOISE_70 = colorVar("turquoise", 70);

// ─── Color: Aqua ────────────────────────────────────────────────────────────

export const AQUA_20 = colorVar("aqua", 20);
export const AQUA_60 = colorVar("aqua", 60);
export const AQUA_70 = colorVar("aqua", 70);

// ─── Color: Ultramarine ─────────────────────────────────────────────────────

export const ULTRAMARINE_20 = colorVar("ultramarine", 20);
export const ULTRAMARINE_60 = colorVar("ultramarine", 60);
export const ULTRAMARINE_70 = colorVar("ultramarine", 70);

// ─── Color: Purple ──────────────────────────────────────────────────────────

export const PURPLE_20 = colorVar("purple", 20);
export const PURPLE_60 = colorVar("purple", 60);
export const PURPLE_70 = colorVar("purple", 70);

// ─── Color: Pink ────────────────────────────────────────────────────────────

export const PINK_20 = colorVar("pink", 20);
export const PINK_60 = colorVar("pink", 60);
export const PINK_70 = colorVar("pink", 70);

// ─── Color: Gray ────────────────────────────────────────────────────────────

export const GRAY_20 = colorVar("gray", 20);
export const GRAY_30 = colorVar("gray", 30);
export const GRAY_40 = colorVar("gray", 40);
export const GRAY_50 = colorVar("gray", 50);
export const GRAY_60 = colorVar("gray", 60);
export const GRAY_80 = colorVar("gray", 80);
export const GRAY_90 = colorVar("gray", 90);
export const GRAY_110 = colorVar("gray", 110);

// ─── Spacing ────────────────────────────────────────────────────────────────

export const SP_1PX = spaceVar("1px");     // 1px
export const SP_0_25 = spaceVar("0.25");   // 2px
export const SP_0_5 = spaceVar("0.5");     // 4px
export const SP_0_75 = spaceVar("0.75");   // 6px
export const SP_1 = spaceVar("1");          // 8px
export const SP_1_25 = spaceVar("1.25");   // 10px
export const SP_1_5 = spaceVar("1.5");     // 12px
export const SP_2 = spaceVar("2");          // 16px
export const SP_2_5 = spaceVar("2.5");     // 20px
export const SP_3 = spaceVar("3");          // 24px
export const SP_4 = spaceVar("4");          // 32px
export const SP_5 = spaceVar("5");          // 40px
export const SP_6 = spaceVar("6");          // 48px
export const SP_7 = spaceVar("7");          // 56px
export const SP_8 = spaceVar("8");          // 64px
export const SP_10 = spaceVar("10");        // 80px

// ─── Radius ─────────────────────────────────────────────────────────────────

export const RADIUS_NONE = radiusVar("none");
export const RADIUS_SM = radiusVar("sm");
export const RADIUS_MD = radiusVar("md");
export const RADIUS_LG = radiusVar("lg");
export const RADIUS_PILL = radiusVar("pill");
export const RADIUS_CIRCLE = radiusVar("circle");

// ─── Border Width ───────────────────────────────────────────────────────────

export const BW_SM = borderWidthVar("sm");
export const BW_MD = borderWidthVar("md");

// ─── Elevation ──────────────────────────────────────────────────────────────

export const ELEVATION_00 = elevationVar("00");
export const ELEVATION_01 = elevationVar("01");
export const ELEVATION_02 = elevationVar("02");
export const ELEVATION_03 = elevationVar("03");
export const ELEVATION_04 = elevationVar("04");
export const ELEVATION_05 = elevationVar("05");
export const ELEVATION_06 = elevationVar("06");

// ─── Font Family ────────────────────────────────────────────────────────────

export const FONT_PRIMARY = "'Geist', sans-serif";
export const FONT_CODE = "'Roboto Mono', monospace";
// ─── Typography Blocks ──────────────────────────────────────────────────────
// Each constant is a CSS block: font-size + line-height + font-weight as var() refs.

// Display: light weight, large sizes
export const TYPE_DISPLAY_01 = typeBlock("display", "01");  // 78px/104px/300
export const TYPE_DISPLAY_02 = typeBlock("display", "02");  // 60px/80px/300
export const TYPE_DISPLAY_03 = typeBlock("display", "03");  // 48px/64px/300

// Heading: medium weight
export const TYPE_HEADING_01 = typeBlock("heading", "01");  // 40px/52px/500
export const TYPE_HEADING_02 = typeBlock("heading", "02");  // 32px/40px/500
export const TYPE_HEADING_03 = typeBlock("heading", "03");  // 24px/32px/500
export const TYPE_HEADING_04 = typeBlock("heading", "04");  // 20px/28px/500
export const TYPE_HEADING_05 = typeBlock("heading", "05");  // 16px/24px/500
export const TYPE_HEADING_06 = typeBlock("heading", "06");  // 14px/20px/500
export const TYPE_HEADING_07 = typeBlock("heading", "07");  // 12px/16px/500

// Body: regular weight
export const TYPE_BODY_01 = typeBlock("body", "01");        // 16px/24px/400
export const TYPE_BODY_02 = typeBlock("body", "02");        // 14px/20px/400
export const TYPE_BODY_03 = typeBlock("body", "03");        // 12px/16px/400

// UI
export const TYPE_UI_01 = typeBlock("ui", "01");            // 24px/32px/400
export const TYPE_UI_02 = typeBlock("ui", "02");            // 11px/16px/500

// Caption
export const TYPE_CAPTION_01 = typeBlock("caption", "01");  // 11px/16px/400

// Badge
export const TYPE_BADGE_01 = typeBlock("badge", "01");      // 14px/20px/400

// Code
export const TYPE_CODE_01 = typeBlock("code", "01");        // 14px/20px/400
export const TYPE_CODE_02 = typeBlock("code", "02");        // 12px/16px/400
